### ISSUE TITLE
Bear creates compilation database but with some files missing from it.

### ISSUE THREAD

**Issue by AndreasGe0** [rizsotto/Bear#132]
Hello ,

I have implement an AST visitor and I am using bear to create a compilation database for TIFF 3.8.1 project. Most files are generated ok but some files are missing from the compilation database. Am running bear on ubuntu 16.04 on Virtual Box. When I dowlonoaded the TIFF 3.8.1 I did the following steps:
./configure
bear make

**Comment by rizsotto** [comment]
thanks for the report Andreas. will look at it later, since i'm traveling at the moment.

**Comment by AndreasGe0** [comment]
Hi, 
Before looking if something is wrong with bear, since am not familiar with these tools at all, I would like to ask if it is possible to skip some files because of the operating system dependencies for example ?? 
Although I have downloaded FFMPEG and LIBTIFF for ubuntu. 
Thank you again

**Comment by rizsotto** [comment]
hi Andreas,

missing files can be cause by multiple reasons:
- some file is not compiled because platform issues. (different OS or HW can be ignored by the build itself: like a intel-windows specific source won't be compile on arm-linux)
- Bear ignores some compilations too:
  - when the compiler is not recognized (`distcc`, `ccache` or other compiler wrappers are not recognized)
  - when the source file is not recognized by its extension (check the `bear/main.py.in` file `is_source` method what are the known extensions.)
  - when the compiler call was not compilation (eg: preprocessor calls are ignored)
  - when the source file is missing after compilation (build processes might generate source file, compile and delete. eg.: gcc does this.)

if you run `bear -n <build cmd>` it generates a verbose JSON file (which is not a compilation database), you can check that the missing file was involved in the build or was ignored by the post-processing step of Bear.

**Comment by AndreasGe0** [comment]
Dear László,

I have recheck the bear make command, and I found out that there is an error during my building process  of ffmpeg 0.6, so it might be causing the "missing files from the compilation database issue". Whenever I have something new I will let you know.

**Comment by rizsotto** [comment]
please reopen this ticket if you found something fishy... also, please provide more information about what context you were noticed the problem. (what os? which distro? what version? what version of Bear? did you installed it? how? (from package or from source) security mechanism is enabled on your os?) all the best
