### ISSUE TITLE
Compilation database empty when compiling, then assembling

### ISSUE THREAD

**Issue by bstaletic** [rizsotto/Bear#146]
With GNU Make, if a user wants to stop gcc after compiling (i.e. after it generated assembly files) and then generate object file from the assembly file it will result in an empty `compilation_database.json`.

The code could be trivial:
```c
void main(void){}
```
And the `Makefile` could be as simple as this:
```Makefile
test: test.o
        $(CC) $< -o $@

test.s: test.c
        $(CC) -S $< -o $@

test.o: test.s
        $(CC) -c $< -o $@
```

The output of `bear make`:
```json
[]
```

The output of [`bear --disable-filter make`](https://paste.pound-python.org/show/RNnegXUFP8Fk5aio2OjU/)

**Comment by rizsotto** [comment]
Yes, it's a valid point you've raised. This issue was recently raised by other users too. Went to the Clang mailing list and got confirmation that it's a valid use case.
On `devel` branch there is a commit which fix your problem partially. It will show the second compilation (from .s to .o) in the output. But I guess you would like to see the first one (from .c to .s) too. Is that correct?

**Comment by bstaletic** [comment]
> I guess you would like to see the first one (from .c to .s) too. Is that correct?

Yes. That is correct. That part is actually the only important part for me, as I use  assembly files just to confirm that thte compiler isn't doing something odd. Thanks for the reply.

**Comment by rizsotto** [comment]
Thanks to confirm it. I can do a really quick fix on `devel` branch. Would that be enough for you?

**Comment by bstaletic** [comment]
That would be great. Thanks in advance.

**Comment by bstaletic** [comment]
I have just confirmed that it works. It successfully made the database for the `Makefile` in the first message.

But I've also noticed something else.

If the Makefile is the same as above, `bear` from devel branch generates:
```json
[
    {
        "command": "cc -c -S -o test.c",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.c"
    },
    {
        "command": "cc -c -S -o test.s",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.s"
    },
    {
        "command": "cc -c -o test.o test.s",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.s"
    }
]
```

But if I make a change to the line of `Makefile` doing the assembly and make Makefile look like:
```Makefile
test: test.o
        $(CC) $< -o $@

test.s: test.c
        $(CC) -S $< -o $@

test.o: test.s
        $(AS) $< -o $@
```

`bear` will generate:
```json
[
    {
        "command": "cc -c -S -o test.c",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.c"
    },
    {
        "command": "cc -c -S -o test.s",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.s"
    }
]
```

In other words, if GNU's assembler (`AS`) is called directly, the following is not captured:
```
    {
        "command": "cc -c -o test.o test.s",
        "directory": "/home/bstaletic/Temp",
        "file": "/home/bstaletic/Temp/test.s"
    }
```

Also, the first captured command seems like it is saying that its output is `test.c` which can't be correct.

Am I missing something here?

**Comment by rizsotto** [comment]
yes, i made an early commit, which is broken. working on the fix now.

**Comment by rizsotto** [comment]
Sorry about it, but you are right. This is not as simple as I've thought. :) Maybe that's why was not released this change yet... Bear currently is not aware of output files. What it does, it filters out some flags, but don't have the any semantic about those. And since from the `cc -S test.c -o test.s` command it thinks both `test.c` and `test.s` are both input files, it generates entries for both and leave the `-o` there... I need to sleep now, but will work on it this week.

**Comment by bstaletic** [comment]
Alright, thanks anyway. Sorry for bothering and if I realise I have some time I'll look into this as well.

**Comment by rizsotto** [comment]
This is fixed in 2.3.4. Sorry for taking too long. And please reopen if you find issue with it.

**Comment by bstaletic** [comment]
Worked perfectly. Thanks for your time.

**Comment by rizsotto** [comment]
Hi @bstaletic -- an update on the assembler side of this. The upcoming Bear 4.1.6 adds first-class recognition of the standalone assemblers `nasm`, `yasm`, and `fasm`, so assembly-only builds and mixed C/asm builds now get per-file entries (useful for asm-lsp and similar).

On your specific repro: the `$(CC) -S foo.c -o foo.s` step is an ordinary C compilation and is recorded. The follow-up `$(CC) -c foo.s` assembles a `.s` file through the compiler driver -- a `.s` input is not a translation unit a language server indexes, so it is intentionally not given its own entry. The GNU assembler `as` itself is likewise deliberately not recognized, because gcc and clang invoke it internally on a temporary `.s` for every normal compile; recognizing it would pollute the database with one throwaway entry per source file.

If you can, it would help a lot to test the release candidate before it ships. Check out the `4.1.6-rc` branch and install from source following [INSTALL.md](https://github.com/rizsotto/Bear/blob/4.1.6-rc/INSTALL.md), then run your usual build under it and let me know whether `compile_commands.json` now looks right.
