### ISSUE TITLE
Bear and CUDA

### ISSUE THREAD

**Issue by cassebas** [rizsotto/Bear#174]
Hi, I'm using Emacs with rtags, which is great. But I'm doing a project with the NVidia CUDA library now, and I can't seem to generate a correct compile_commands.json by bear.
The CUDA library has its own compiler (nvcc), input files are with a .cu extension.

I tried running $ bear --use-c++ /opt/cuda/bin/nvcc, but that didn't work, my compile_commands.json is an empty [].
Any ideas?
Thnxs!

**Comment by rizsotto** [comment]
Thanks for the report. I was never tested Bear against the cuda compiler wrapper myself. The `--use-cc` and the `--use-c++` shall address this use case as you found it... If you can provide a more verbose output of the run that would help to identify the missed compilation database entries... A command like `$ bear -vvvv --use-cc /opt/cuda/bin/nvcc --use-c++ /opt/cuda/bin/nvcc ...` might suite for that job.

**Comment by cassebas** [comment]
Thnxs for your help. I just ran the command you proposed. Attached is the output, hope it's any good:)
Please let me know if I can provide more information.
[bear_verbose_output-make_with_nvcc.txt](https://github.com/rizsotto/Bear/files/1348926/bear_verbose_output-make_with_nvcc.txt)

**Comment by rizsotto** [comment]
Thanks to come back! From the report I see that Bear does not recognize the `.cu` files as source, therefore it does not put them into the final report. Can you confirm that those files are the source files you want to see in the compilation database?

Before I make the change to accept `.cu` files as source files. Can you give a try to modify the `classify_source` method in `main.py.in:536`? You can run the same command as before and validate that the output is not empty. But I'm more interested that, can tools use the compilation database for such files?

**Comment by cassebas** [comment]
I succeeded in generating a `compile_commands.json` (attached as a txt file). The `.cu` files are actually C++ files in my case. I'm afraid that I'm still not able to generate tags after this. The error I get is (although I probably should ask the rtags developer:)

`vectorAdd % rc -J`
`[Server] Compilation failed to load.`

Thnxs for your help!

[compile_commands_json.txt](https://github.com/rizsotto/Bear/files/1350192/compile_commands_json.txt)

**Comment by rizsotto** [comment]
Please let me understand what you've done. Did you just rename the `.cu` file to `.cpp`? And then got the compilation database as you've sent it. But it still not working with rtags. Is that correct?

**Comment by cassebas** [comment]
Sorry, I wasn't very clear. I did what you suggested, I modified the `classify_source` method in `bear` by adding the `.cu` extension (mapped to C++). That gave me a non-empty `compile_commands.json` (the one I attached above). I am not sure if this is the correct compile_commands.json.

My guess is that rtags doesn't handle `.cu` very well either.

**Comment by cassebas** [comment]
I just realized I might have made an error by sending you the wrong compile_commands.json. After running the modified `bear` I did get a compile_commands.json with a vectorAdd.cu. But then `rtags` wouldn't index my sources so I indeed tried to rename the `.cu` to `.cpp` (also in the Makefile). That didn't help either I'm afraid for `rtags` to work.

My apologies for the confusion! 
If you'd like a correct compile_commands.json (with `bear` modified like you suggested), let me know (and I can run it again tonight).

**Comment by rizsotto** [comment]
I've noticed that the two files are not in sync. ;)

If you could send the verbose logs from Bear and the output compilation database that would let us think further... Because I'm not 100% sure that it's the problem with `rtags`. It could be that the compilation database contains only the wrapper call, which does not contains all the neccessary compiler flags. (This is the case for MPI compiler wrapper.)

And we can also can think from the other direction: from the Bear logs we can manually write a compilation database which make `rtags` happy. That would be a lead how to fix Bear.

**Comment by cassebas** [comment]
Ok then, here I am again:-)
Attached you find the new `compile_commands.json` and the output I got (with some extra output to show what I've done). Hope it helps, thnxs again!

[compile_commands_json.txt](https://github.com/rizsotto/Bear/files/1360490/compile_commands_json.txt)
[ouput-bear-nvcc.txt](https://github.com/rizsotto/Bear/files/1360491/ouput-bear-nvcc.txt)

**Comment by rizsotto** [comment]
Thanks to come back with it. I do appreciate your help to investigate this case.

I've seen similar problem with the OpenMPI compiler wrappers. These wrappers are doing quiet complex things before acutally calling the compiler. But the OpenMPI wrappers are having a command line switch to query what compiler flags they add before they call the compiler. I don't think it will be possible with the CUDA wrappers. Mainly, because they call the compiler multiple times.

But one thing I've noticed, before the wrapper calls the compiler for different targets, it make a preprocessing call. (I presume they want to guarantee that it's the same thing compiled for all targets.) These are the lines:

`bear: DEBUG: _split_command: input was: ['g++', '-E', '-x', 'c++', '-D__CUDACC__', '-D__NVCC__', '-I../../common/inc', '-I/opt/cuda/bin/..//include', '-D__CUDACC_VER__=80061', '-D__CUDACC_VER_BUILD__=61', '-D__CUDACC_VER_MINOR__=0', '-D__CUDACC_VER_MAJOR__=8', '-include', 'cuda_runtime.h', '-m64', 'vectorAdd.cu']`
`bear: DEBUG: _split_command: input was: ['g++', '-D__CUDA_ARCH__=610', '-E', '-x', 'c++', '-DCUDA_DOUBLE_MATH_FUNCTIONS', '-D__CUDACC__', '-D__NVCC__', '-I../../common/inc', '-I/opt/cuda/bin/..//include', '-D__CUDACC_VER__=80061', '-D__CUDACC_VER_BUILD__=61', '-D__CUDACC_VER_MINOR__=0', '-D__CUDACC_VER_MAJOR__=8', '-include', 'cuda_runtime.h', '-m64', 'vectorAdd.cu']`

Not sure about the outcome, but if you could call Bear like this: `bear make` might end up to have these lines in the compilation database. (Notice that you don't specify the `--use-cc` flag.) You need two modifications on Bear: need to accept the `.cu` files as source files (you've done that already) and accept preprocessing calls too (`main.py.in:493` delete the `'-E'` from the set and add to the other set 2 lines bellow).

And even if this does not do it, you can manually create the compilation database with an editor, to check is `rtags` is happy with what it sees. Then we can know that the problem is in the Bear generated files or not.

**Comment by cassebas** [comment]
Hi, sorry for the delay, I been kinda busy:)
I did what you asked, the `compile_commands.json` is somewhat bigger now but `rtags` still doesn't like it. Attached you find the output of running `bear -vvvv make` and the `compile_commands.json`. Hope it helps!

The output also shows a  `diff` of the `bear` program for clarity (or better verification;-).

[output-bear-make-nvcc.txt](https://github.com/rizsotto/Bear/files/1376748/output-bear-make-nvcc.txt)
[compile_commands_json.txt](https://github.com/rizsotto/Bear/files/1376749/compile_commands_json.txt)

**Comment by rizsotto** [comment]
No worries, thank to continue the investigation with me.

Your change looks good, that's what I was thinking. And the output looks good to me too. (Except that it has `-E` and `-c` in the same line. Maybe try to remove one of them from the output. Will fix it in the code later.)

So, you can take those commands from the compilation database and execute them in a shell. (You need to change working directory according to the `directory` field, and execute the `command` field.) If the compiler fails than you need to figure out what it's missing.

If the compiler test pass, you try out a different tool than `rtags`. (Like `clang-check` or `clang-format`) Maybe those tools reports the error better.

**Comment by rizsotto** [comment]
Sorry for the long delay... The recently released 2.4.3 version supports CUDA.
Please create new ticket if you have problem to use that.
