### ISSUE TITLE
"newlocale: No such file or directory" when en_US.UTF8 locale not present

### ISSUE THREAD

**Issue by bartlibert** [rizsotto/Bear#182]
I'm running a Debian system where the default locale is en_GB.UTF-8. The en_US.UTF-8 locale is not installed. 
When I run "bear make", I get the following error:

`bear: newlocale: No such file or directory `

If I install the en_US.UTF-8 locale, everything works.

I wrote a quick test program myself, with a line of code similar to this one: https://github.com/rizsotto/Bear/blob/7fe794fac44c09b9d3fadecde3ff7e51a6d59a40/libear/ear.c#L198
By changing the locale string in the newlocale call to a locale that is not installed on the system, I can reproduce the issue.

**Comment by rizsotto** [comment]
Bart thanks for the report. This code is new in Bear, I need to learn how to use the `newlocal`. ;) Will look at it later this week.

**Comment by rizsotto** [comment]
Hey Bart, was trying to fix this issue. Now it passes my basic tests on different linux distros with different locales. Could you check that it works for you too? The change is not merged to `master` yet (it's on a branch called `fix`).

**Comment by bartlibert** [comment]
It works for me. Thanks for the quick fix!

**Comment by rizsotto** [comment]
Thanks to come back with the good news. Will release it soon.

**Comment by sebastinas** [comment]
FWIW, instead of using `en_US.UTF-8`, you could also use `C.UTF-8`. It is guaranteed to be available since (e)glibc 2.13.

**Comment by rizsotto** [comment]
Hey Sebastian, the current master is using `newlocale(LC_CTYPE_MASK, "", (locale_t)0)`. Which according to the man page:
> An implementation-defined native environment corresponding to the values of the LC_*  and LANG environment variables (see locale(7)).

**Comment by timblaktu** [comment]
I'm also seeing this issue on Debian Jessie 8.7(using en_US.UTF-8), GNU Make 4.0, running Bear built from the 2.3.9 tag. Since this tag/release was 15 days ago and this issue was fixed on same day, I originally ASSumed the fix was included in that release.

To verify, I then checked out, built and installed _master_, and re-built my source code (with make, which I've simply aliased in .profile to _bear make_.. let me know if there's a better best practice for this), and...

I am still getting the newlocale error:

`libear: (/usr/local/src/Bear/libear/ear.c:200) newlocale: No such file or directory`

 These are my locale settings:

```
/usr/local/src/Bear > locale -a                                                         master
C
C.UTF-8
en_US.utf8
POSIX
/usr/local/src/Bear > locale                                                            master
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I tried to change my locale to C.UTF-8 (as @sebastinas suggests), just locally in my shell before invoking make, like so:

`export LANG=C.UTF-8; make mytaget`

(I couldn't change the locale using `dpkg-reconfigure locales` bc it doesn't show "C.UTF-8" as an installed option, even though locale -a does.)

and I'm still getting the same error. I just wanted to let you know that I was still encountering this issue, and also to seek help for getting past it. Thank you.
