### ISSUE TITLE
Question: is there a way to generate JSON DB for a single file?

### ISSUE THREAD

**Issue by damnskippy** [rizsotto/Bear#188]
Is there a way to manually generate JSON DB for a single source file?
If I currently do, 
`$ gcc <lots of options> -c foo.c`
can I feed just this line to bear somehow to output compile_commands.json file?
Thank you.

**Comment by damnskippy** [comment]
To be complete, I'm dealing with a gnarly make system that calls several internal scripts, and ultimately I'm still digging to figure out how to feed all of that into Bear neatly.
For now however I do know the final command line for a given source file, and so I wondered if there's a way to feed that to bear.
FWIW I tried the following (just a shot in the dark without knowing it's the right thing or not):
`$bear --libear path/libear.so -use-cc="path-to-compiler bazillion-gcc-options" -c foo.c`
but however ran into the following error in run_build():
```
  File "/volume/hab/Linux/Ubuntu-12.04/x86_64/python/2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 36] File name too long
```
Hence I was just wondering if I could invoke bear directly on the gcc command line, instead of on make.
Thanks.

**Comment by rizsotto** [comment]
Thanks for the question. (It looks like I need to write a FAQ page or update the README file, because you are not the first one. ;))

The answer is: No. Bear does not support single compiler calls to log into the compilation database. The reason for that, if you handcraft the command line, with the same effort you can write the compilation database entry by yourself. (Instead of type it into the shell prompt, you type into an editor.)

Here are the workarounds if you still want it.... Instead of call the compiler, call a shell which will call the compiler: `bear sh -c "gcc -c foo.c"` if you need to pass environment variables, call it like this: `ENV1=VAR1 bear sh -c "gcc -c foo.c`.

I would also recommend to install Bear (from package of from source), and then you will need not to pass the `--libear path/libear.so`.

I would also not recommend to abuse the `--use-cc` with compiler arguments. This flag is used to recognise the compiler (which is not known by Bear by default). Passing compiler arguments will prevent the match. Because this is not what Bear shall use as compiler. Bear does not invokes compilers directly, your build does. It just has to recognise from many program execution, which one was a compiler call.

Finally I recommend to run the whole build (does not matter how nasty the build script is). This tool is designed to find the compiler calls from many command execution. Just call `make clean && bear make` then inspect the `compile_commands.json` file. If you use a compiler which is not recognised by Bear, you can call like this: `make clean && bear --use-cc=xcc make` where your compiler was called `xcc`. If your case is not simple, I would like to hear more about the difficulties in order to help you.

**Comment by damnskippy** [comment]
Thanks - that's very helpful!
