### ISSUE TITLE
Revisit: Absolute path request.

### ISSUE THREAD

**Issue by maindoor** [rizsotto/Bear#240]
Revisiting issue: https://github.com/rizsotto/Bear/issues/238
Since I can't change the State of that issue to reopen, I am opening a New-Issue.
Refer the original issue above for the problem and this issue for updated comments.

**Comment by maindoor** [comment]
I tried this again with version bear 2.3.13 (compiled from git) on an open source project (openwrt).
Please see an entry for a file txrx.c below.
The compiler is still "mips-openwrt-linux-musl-gcc". Can we have
an option to output full (absolute path) instead of just the name of the end executable ?

{
"arguments": [
"mips-openwrt-linux-musl-gcc",
"-c",
"-Wp,-MD,/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/drivers/net/wireless/ath/ath10k/.txrx.o.d",
"-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/",
"-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/uapi",
"-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include/",
"-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include/uapi",
"-include",
"/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/backport-include/backport/backport.h",
"-Wno-unused-but-set-variable",
"-DCPTCFG_VERSION="v4.19.23-1-0-g480a925a"",
"-DCPTCFG_KERNEL_VERSION="v4.19.23-0-g67d52fae61c1"",
"-DCPTCFG_KERNEL_NAME="Linux"",
"-I./arch/mips/include",
"-I./arch/mips/include/generated",
"-I./include",
"-I./arch/mips/include/uapi",
"-I./arch/mips/include/generated/uapi",
"-I./include/uapi",
"-I./include/generated/uapi",
"-include",
"./include/linux/kconfig.h",
"-D__KERNEL__",
"-DVMLINUX_LOAD_ADDRESS=0xffffffff80060000",
"-DDATAOFFSET=0",
"-Wall",
"-Wundef",
"-Wstrict-prototypes",
"-Wno-trigraphs",
"-fno-strict-aliasing",
"-fno-common",
"-fshort-wchar",
"-Werror-implicit-function-declaration",
"-Wno-format-security",
"-std=gnu89",
"-fno-PIE",
"-mno-check-zero-division",
"-mabi=32",
"-G",
"0",
"-mno-abicalls",
"-fno-pic",
"-pipe",
"-mno-branch-likely",
"-msoft-float",
"-DGAS_HAS_SET_HARDFLOAT",
"-Wa,-msoft-float",
"-ffreestanding",
"-fno-stack-check",
"-march=mips32r2",
"-mtune=34kc",
"-Wa,--trap",
"-DTOOLCHAIN_SUPPORTS_VIRT",
"-I./arch/mips/include/asm/mach-ath79",
"-I./arch/mips/include/asm/mach-generic",
"-fno-asynchronous-unwind-tables",
"-fno-delete-null-pointer-checks",
"-Wno-frame-address",
"-Wno-format-truncation",
"-Wno-format-overflow",
"-Wno-int-in-bool-context",
"-Os",
"-Wno-maybe-uninitialized",
"-fno-caller-saves",
"--param=allow-store-data-races=0",
"-DCC_HAVE_ASM_GOTO",
"-Wframe-larger-than=1024",
"-fstack-protector",
"-Wno-unused-but-set-variable",
"-Wno-unused-const-variable",
"-fomit-frame-pointer",
"-fno-var-tracking-assignments",
"-Wdeclaration-after-statement",
"-Wno-pointer-sign",
"-fno-strict-overflow",
"-fno-merge-all-constants",
"-fmerge-constants",
"-fno-stack-check",
"-fconserve-stack",
"-Werror=implicit-int",
"-Werror=strict-prototypes",
"-Werror=date-time",
"-Werror=incompatible-pointer-types",
"-Werror=designated-init",
"-fno-pie",
"-no-pie",
"-I/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/include",
"-iremap/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1:backports-4.19.23-1",
"-DMODULE",
"-mno-long-calls",
"-DKBUILD_BASENAME="txrx"",
"-DKBUILD_MODNAME="ath10k_core"",
"-o",
"/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.o",
"../backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.c"
],
"directory": "/home/bmantle/proj/openwrt/build_dir/target-mips_24kc_musl/linux-ar71xx_tiny/linux-4.14.103",
"file": "../backports-4.19.23-1/drivers/net/wireless/ath/ath10k/txrx.c"
}

**Comment by rizsotto** [comment]
Thanks to coming back. (I was not aware that you can't re-open issue, after it's closed. It has been a recent change on the site, because I recall people did that in this project. Sorry about that.)

Could you confirm that the original build was executing the compiler with full path? To my best understanding of the code I've wrote months ago, it's not throwing away the full path of the compiler. It just outputs how it was executed. (So, if the build system was executing as `mips-openwrt-linux-musl-gcc -c ...` the output will contains only `mips-openwrt-linux-musl-gcc`. But if it was `/opt/bin/mips-openwrt-linux-musl-gcc -c ...` the output will contains `/opt/bin/mips-openwrt-linux-musl-gcc`.)

So, please help me to clarify these two things:
- The build script was calling `mips-openwrt-linux-musl-gcc -c ...`?
- Even if the build script was calling like that, you would like to have the compiler with full path?

**Comment by hubgitname** [comment]
> Sorry about that.
Please don't be. If anything, I must be thankful for such a tool. I'm just trying to see if I can improve the
tool. I couldn't find a way to re-open that's why...

I can definitely confirm the build script was calling just mips-openwrt-linux-musl-gcc. It is possible
that the PATH variable was modified during the build to find mips-openwrt-linux-musl-gcc. But the tools
that might use compile_commands.json, like an editor, might necessarily not see the modified PATH variable and so will not find mips-openwrt-linux-musl-gcc. 

> Even if the build script was calling like that, you would like to have the compiler with full path?
Yes, please. Given the above observations. When I fixed the full path manually in compile_commands.json,
everything fell in place.
Also please see the entry for bear here for further inspiration in adding this option:
https://github.com/Andersbakken/rtags/wiki/Usage

**Comment by rizsotto** [comment]
I see now, thanks to clarify this for me. (I'm doing very little cross-compilation myself, so I don't know what are the constraints or the workflow for such project.)

Anyway, about the problem. This is a hard one! :smile: As you mentioned, the build script might set up a `PATH` environment, which is only valid during the build.

1. One option can be to capture the `PATH` environment and pass it to the post-processor. The drawback for this, that if the give directory is only visible when the execution happens (bazel do bind mount before calling the compiler) the post processor won't be able to resolve the compiler.
1. The other option is to resolve the path to the compiler right away when the execution happens. The drawback for this, the `LD_PRELOAD` function can't do complex task like this.
1. The third option, (which I'm leaning towards) is to rework the current architecture. I already started this work, where the `libear` library is not execute the requested program, but a wrapper (which has way less restrictions what it can do). The wrapper then calls the real program and log the execution (with full path this case).

About the timing, the 3rd option can happen months later. The 1st one can be hacked pretty fast. I'm happy to get pull-request for the 1st one (with some tests around). :smile: But I would like to spend my time on the refactoring which I'm doing for a while already.

**Comment by hubgitname** [comment]
If it is a hard one to address, pls don't bother. I can write a script to handle this. Great tool otherwise. Feel free to close this issue.

**Comment by rizsotto** [comment]
Thanks. Will keep open the ticket to remember to implement it in the new version.
As a workaround, probably the easiest if you can change the build to use the compiler with absolute path, then you don't need to post process the output.

**Comment by rizsotto** [comment]
There is a release candidate on master branch now, which suppose to fix this issue. Could you give it a try for that?

I'm closing this ticket now, but will re-open if the bug still there.

**Comment by Str1ker17** [comment]
Hello, 

> There is a release candidate on master branch now

What version should I use to overcome this limitation and get full compiler path in output?

**Comment by rizsotto** [comment]
@Str1ker17 please try the latest release (3.0.17).
