### ISSUE TITLE
with parallel make, compile_commands.json gets corrupted

### ISSUE THREAD

**Issue by djcb** [rizsotto/Bear#242]
### Expected Behavior

I'm compiling a fairly big autotools project with bear; this general works, with  something like 
```
   ./configure CXX="bear --cdb=$(pwd)/compile_commands.json g++"
```
after running e.g. `make -j10`, I'd expect to have a fully filled `compile_commands.json`. Note the `-j10` means a parallel `make` with up to 10 things happen in parallel.

### Actual Behavior

`compile_commands.json` gets corrupted or perhaps read at a moment where it does not contain valid json:
```
make[1]: *** [Makefile:1691: libloopy_la-loop.lo] Error 1
Traceback (most recent call last):
  File "/usr/bin/bear", line 739, in <module>
    sys.exit(intercept_build())
  File "/usr/bin/bear", line 265, in wrapper
    return function(*args, **kwargs)
  File "/usr/bin/bear", line 297, in intercept_build
    entries = iter(set(itertools.chain(previous, current)))
  File "/usr/bin/bear", line 672, in load
    for entry in json.load(handle):
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5178 column 35 (char 191860)
```
looking at the given location indeed shows some incomplete json. I tried with `--append` as well, with similar results.

It does work with `make -j1`, but that makes the build so much slower that I'd like to avoid that.

I suspect some locking is needed of the output file. 

### Environment
- bear 2.3.13 (distro version) on Debian/SID

**Comment by rizsotto** [comment]
Hey @djcb , thanks for the report. Unfortunatelly Bear was not intended to used as a compiler wrapper. It's just a pure luck, that it works with sequential execution. :smile: Where have you read that this usage is supported? (I would ping the author of that page to change the documentation, because it's not correct.)

What are you trying to achieve? Why do you want to intercept the configure step? If you want to intercept the configure step (which I would not do), you can just write `bear ./configure`. If you want to intercept the build (which was the main goal of this tool), you can just write `bear make -j8`. (And that shall work if the build is parallel.)
