### ISSUE TITLE
quotes not escaped in "agruments"

### ISSUE THREAD

**Issue by zhangxiaobin2** [rizsotto/Bear#265]
With the related issue: https://github.com/rizsotto/Bear/issues/88

When the compile command is like -DABC=\\"abc\\", it will write to json file like:
[
    {
        "agruments":[
            "gcc",
            "test.c",
            "-DABC=\\"abc\\""
        ]
    }
]

But when we read the json file with json.load() method,  we get the string value as : 
**-DABC="abc"**, it espaced the  **\”**,  but I want to keep the **\\** in the string. When we use the option in the command line,  the compiler consider ABC as **abc**, not as **string "abc"**. It's not what I want.

### Expected Behavior
json file:
[
    {
        "agruments":[
            "gcc",
            "test.c",
            "-DABC=\\\\\\"abc\\\\\\\""
        ]
    }
]

read from the json file as command line:
gcc test.c -DABC=\\"abc\\"

### Actual Behavior
json file:
[
    {
        "agruments":[
            "gcc",
            "test.c",
            "-DABC=\\"abc\\""
        ]
    }
]

read from the json file as command line:
gcc test.c -DABC="abc"

I can see you have already fix the similar issue with "command" key , reference to: https://github.com/rizsotto/Bear/issues/88.

But it's still appear in the newest version with the key "agruments" in the json file.
So, can you fix it in the newest version?

Thanks

**Comment by rizsotto** [comment]
@zhangxiaobin2 , sorry for the late answer.

I've just added a new test specific to this scenario.

The original command was like this:

```shell
$ clang++ '-DMESSAGE="Hello World\n"' -o hello src/main.cpp
$ ./hello
Hello World
$ rm ./hello
```

The command could have been written as `clang++ -DMESSAGE=\"Hello\ World\\\n\" -o hello src/main.cpp`. It does the same thing. The difference is how we want to escape the argument for the shell.

Then took the expected compilation database, which was look like this:

```json
[
    {
        "arguments": ["c++", "-c", "-DMESSAGE=\"Hello World\\n\"", "-o", "hello", "src/main.cpp"],
        "directory": ".",
        "file": "src/main.cpp"
    }
]
``` 

To re-run the command from Python as:

```python
import json
import subprocess

with open('result.json', 'r') as f:
  content = json.load(f)

args = content[0]["arguments"]
subprocess.check_call(args)
```

And because this only produce an object file, was need to run a few other commands:

```shell
$ mv hello hello.o
$ clang++ -o hello hello.o
$ ./hello
Hello world
$
```

Closing this now. I am pretty confident it deals with the quotes correctly. Feel free to add more comments or suggest other validation methods. You can also add new test as a PR.
