### ISSUE TITLE
Could Bear work with other build wrapper?

### ISSUE THREAD

**Issue by bloodlee** [rizsotto/Bear#274]
Hi,

this is a question not an issue

We are using SonarCFamily plugin to scan the source code defect and this plugin has its own build wrapper, which generates different format of compilation database. The usage is similar to Bear, like this
`build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all`.
More details can be found [here](https://docs.sonarqube.org/latest/analysis/languages/cfamily/).

On other purpose, I do need the compilation db generated by Bear as well (Frankly speaking, Bear generates much better compilation db).  But I don't want to compile the project twice (Our code base is huge)

I don't quite understand on how Bear got implemented but I believe it should be similar to the one used by SonarCFamily.
So my question is  - Could Bear work with other build wrapper and generate multiple compilation db by compiling once?

Thanks very much.

**Comment by rizsotto** [comment]
Hi @bloodlee ,

I've never heard about SonarCFamily before, but now I was trying to read their docs. And my understanding is that you need to run the build (with the `build-wrapper`) to capture the commands to run, and then you run the analyzer. Is that right?

In order to answer your question, I need to understand how they "[gathers all the configuration required for correct analysis](https://docs.sonarqube.org/latest/analysis/languages/cfamily/)". Is `build-wrapper-linux-x86-64` a binary executable or a script? I presume it's a binary. So, it's not easy to know how it works.

You can just try `bear -- build-wrapper-linux-x86-64 ...` or the other way around `build-wrapper-linux-x86-64 ... bear ...`. They might work. :)

Where are you planing to save time on your dev loop? Do you run this tool in your CI or on your machine after every build. If you run it on a CI machine, time is not that critical. (I mean many CI server support parallel tasks.)

In the future I'm planing to implement a fast mode for Bear, where it fakes the compiler calls (creates empty object files) and fakes the linker calls (creates empty libraries or executables) in order to avoid the lengthy compilation. Would that help for you?

What are you need the compilation database from Bear? Are you using it for your editor or you run CLang tools, like `clang-tidy` or `clang-format`?

**Comment by bloodlee** [comment]
Hi @rizsotto ,
Thanks for you reply.

For you question - "gathers all the configuration required for correct analysis", I believe the analyzer needs to know the include header path and the preprocessing macros. Yes. build-wrapper-linux-x86-64 is a binary executable. 

Now I use Bear's compilation database for another tool, named PCLint Plus. And I would like to integrate both SonarCFamily and PCLint Plus check into pre-committing flow. It means when creating a pull-request, the server will scan the code. But to generate the correct result, the compilation database needs to be generated, which needs to rebuild the whole project. And since SonarCFamily and PCLint Plus rely on different DBs, now I build the project twice. You can see here. It will waste a lot of server power on it.  And due to the license, no way to use SonarCFamily's DB.

Do you have any suggestion on my situation? BTW, I will try your suggestion to put both wrappers together.

Thanks again.

**Comment by bloodlee** [comment]
I did a quick try. Looks like `build-wrapper-linux-x86-64 ... bear ...` works, the opposites way doesn't.
Bear is great! I will look into how it's implemented and it is very interesting to me.

Many thanks!

**Comment by rizsotto** [comment]
I'm glad that you've achieved what you wanted. :) Will close this ticket then. Feel free to open a new one or re-open this if you have more questions.
