### ISSUE TITLE
Feature request/proposal: mapping compilation dependencies between objects

### ISSUE THREAD

**Issue by maroneze** [rizsotto/Bear#329]
I currently use Bear to produce `compile_commands.json` files for C projects based on make. However, when a `make` target produces several binaries at once, I need to find out, for a given single binary, which sources were used to produce it, and only those (to avoid e.g. multiple definitions of function `main`).

As far as I understand, the lack of such information is a limitation of the JSON Compilation Database format, and not Bear's fault; but since you mention *Build semantics* in the [Roadmap](https://github.com/rizsotto/Bear/wiki/Roadmap), I'd like to know if there already exists something related to this.

Here's a concrete example Makefile, to illustrate what I mean:

```
all: out1 out2
a.o: a.c
b.o: b.c
c.o: c.c
out1: a.o c.o
	$(CC) -DA -o $@ $^
out2: b.o c.o
	$(CC) -DB -o $@ $^
```

I want to find out that, to build `out1`, I only need `a.c` and `c.c`, but not `b.c`.

Currently, this example does not result in a very informative `compile_commands.json`, since the compilations of `out1` and `out2` (which do not include `.c` files) are not listed in the `compile_commands.json`. But even if I short-circuit the `.c -> .o` steps, as in:

```
all: out1 out2
out1: a.c c.c
	$(CC) -DA -o $@ $^
out2: b.c c.c
	$(CC) -DB -o $@ $^
```

In this case, the `compile_commands.json` contains `c.c` twice, with different `-D` arguments each time. I then need to manually reconstruct the compilation graph to find out which command is related to `out1`.

I naively expect that, by retracing the compilation steps (looking for `-o`'s in the command lists, and linking them together), I should get the information I need. But I wonder if this feature is already available somehow in Bear, or if it has already been considered and is in fact much more complex than I expect.

Otherwise, if this seems feasible, would it be useful to try and implement it in Bear? I'd like to contribute back if possible, but I don't know if this kind of information is useful for the project (for instance, in a `build_semantics.json` file). Here's what I'd expect to have at the end:

```
[
    { "arguments": [
        "cc",
        "-o",
        "out1",
        "a.o",
        "c.o"
    ],
      "directory": "/tmp",
      "file": "out1"
    },
    { "arguments": [
        "cc",
        "-o",
        "a.o",
        "a.c"
    ],
      "directory": "/tmp",
      "file": "a.o"
    },
    { "arguments": [
        "cc",
        "-o",
        "c.o",
        "c.c"
    ],
      "directory": "/tmp",
      "file": "c.o"
    }
]
```

In this JSON file, the elements are centered on the *object* files and not the sources, which is somehow dual to the `compile_commands.json` file, and more useful for our use case. Some extra information, such as a `sources` field, could be added to make it even easier to process.

I hope not to be reinventing the wheel, or missing something obvious there.

**Comment by rizsotto** [comment]
Hi @maroneze , thanks for the suggestion. It reminds me (what you've wrote) to just support linking in the compilation database. #276 is the ticket to cover that. Is that correct?

My vision with the build semantic was to produce ontology (with different format than the JSON compilation database) to add all possible informations about a build. (The current JSON format is very limited and tied to Clang needs.) I'm thinking about a solution where we can take a command (with its context) and not reformat this information, but enrich with extra information. So, instead of filtering out commands which does not compile, I would still keep them in the output. And when a compiler call is recognized, I would add the details to the entry (like what is the source file, what C/C++ dialect is it, what compiler pass was probably run on it, what is the output, etc..). In this concept it's much easier to support linking, archive creations or support other languages.

**Comment by maroneze** [comment]
Yes, it's ticket #276, sorry I didn't see it. I'll close this one.

And thanks for the clarification concerning the build semantics. I'll keep an eye on it!
