### ISSUE TITLE
bear 3.0.4 OSX build failure

### ISSUE THREAD

**Issue by chenrui333** [rizsotto/Bear#344]
**Describe the bug**
bear 3.0.4 OSX build failure

**Expected behavior**
build pass 

**Environment:**
 - OS name: osx builds
 - OS version: osx 10.14, 10.15, 11.0
 - OS architecture: x86_64
 - Bear version: 3.0.4
 - Bear install method: build from source

**build error log**

<details>
<summary>build failure</summary>

```
ld: library not found for -labsl_dynamic_annotations
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [intercept/er] Error 1
make[4]: *** [intercept/CMakeFiles/er.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 90%] Built target intercept_a
[ 92%] Linking CXX executable wrapper
ld: library not found for -labsl_dynamic_annotations
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [intercept/wrapper] Error 1
make[4]: *** [intercept/CMakeFiles/wrapper.dir/all] Error 2
[ 92%] Built target citnames_a
make[3]: *** [all] Error 2
make[2]: *** [subprojects/Stamp/BearSource/BearSource-build] Error 2
make[1]: *** [CMakeFiles/BearSource.dir/all] Error 2
make: *** [all] Error 2
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
```

</details>

full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1585304920
relates to https://github.com/Homebrew/homebrew-core/pull/67303

**Comment by rizsotto** [comment]
The problem is with Homebrew packaged `grpc` package. The `pkg-config` file is broken... I've noticed it well, the CI job is failing for macOS, since the `abseil` package version bump.

https://github.com/Homebrew/homebrew-core/pull/62722 This was my attempt to put a more strict test into their harness to prevent failures like this in the future. In this PR you can see the issue can be reproduced by a simple program, and therefore the bug is not Bear.

Unfortunately I don't own an apple product to help fix this issue.

It might worth to Arch linux packages, since they are also using recent version of the `grpc` package and that package has no problem like this.

**Comment by chenrui333** [comment]
I see, thanks @rizsotto, let me see what I can do.
