### ISSUE TITLE
use bear make in freebsd and have error

### ISSUE THREAD

**Issue by AimerYi** [rizsotto/Bear#378]
I build bear in freebsd from github
but when use bear -- make in freebsd
it have an error:
      wrapper: failed with : system call "dlopen " failed : Resource temporarily unavailable.
how can i fix this and use bear in freebsd

**Comment by rizsotto** [comment]
Hey @AimerYi , can you give me more context?

- I might try to reproduce it, but need to know what version of FreeBSD you are working on?
- can you provide a verbose log from the command you've been running? (`bear --verbose -- make` would do it)

**Comment by AimerYi** [comment]
hey @rizsotto 
this is my Freebsd version:
![Uploading 2021-05-24 14-59-20 的屏幕截图-1.png…]()

**Comment by AimerYi** [comment]
Hey @rizsotto  this is freebsd version:
![2021-05-24 14-59-20 的屏幕截图-1](https://user-images.githubusercontent.com/49505827/119309849-77c3a880-bca1-11eb-8de3-4d28cf44cb91.png)
problem:
![2021-05-24 15-09-45 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310303-21a33500-bca2-11eb-9b35-bedb79a7de0b.png)

and this is the verbose log after run the command bear --verbose -- make
![2021-05-24 15-06-37 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310186-fb7d9500-bca1-11eb-9c11-ebfa622f67d5.png)
![2021-05-24 15-07-08 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310105-e143b700-bca1-11eb-9eef-6a9cfe631a21.png)
![2021-05-24 15-07-25 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310118-e56fd480-bca1-11eb-9dd1-c8bd8cfc18c7.png)
![2021-05-24 15-07-42 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310130-ea348880-bca1-11eb-8422-c3187f353bf5.png)
![2021-05-24 15-07-59 的屏幕截图](https://user-images.githubusercontent.com/49505827/119310162-f4ef1d80-bca1-11eb-94e4-3d00abe54662.png)

**Comment by rizsotto** [comment]
Thanks @AimerYi for this.

```C
void *handle = ::dlopen(LIBC_SO, RTLD_LAZY);
if (handle == nullptr) {
  return rust::Err(std::runtime_error(
    fmt::format("System call \"dlopen\" failed: {}", sys::error_string(errno))));
}
```

This is the fragment which cause the error... I presume the `LIBC_SO` definition is not available on FreeBSD. Can you confirm this? Or suggest a similar symbol to it? (For reference [this is what the linux defines](https://code.woboq.org/userspace/include/gnu/lib-names-64.h.html) this.)

As a workaround I can suggest to use the compiler wrappers (instead of the preload). `bear --force-wrapper -- make` is the way to use it.

**Comment by AimerYi** [comment]
sorry i just use freebsd to get it's kernel's compile_commands.json.I don't know how to confirm it.
and if i use bear --force-wrapper -- make to finish the make ,the file: "compile_commands.json" have nothing....

**Comment by AimerYi** [comment]
sorry i just use freebsd to get it's kernel's compile_commands.json.I don't know how to confirm it.
and if i use bear --force-wrapper -- make to finish the make ,the file: "compile_commands.json" have nothing....

**Comment by rizsotto** [comment]
@AimerYi could you test this for me?

- Check what is the filename of the LibC in your system. `ls -l /lib/libc.so*` I assume it's going to be `libc.so.7`
- Edit Bear's `source/libsys/source/Process.cc` line 44 edit the define line to `#define LIBC_SO "libc.so.7"` (I assume you have 3.0.12 Bear source code)
- Compile and install Bear with this change, and run against the kernel compilation.

**Comment by AimerYi** [comment]
- the LibC in the system is libc.so.7
- I change source/libsys/source/Process.cc line 44  to #define LIBC_SO "libc.so.7"
- now I can run the command bear -- make ...  ,and the compile_commands.json have data ,but the bear have a new error ,i'm sure the make can finish. 
- 
![2021-06-03 14-34-23 的屏幕截图](https://user-images.githubusercontent.com/49505827/120599222-ce876a00-c479-11eb-983d-ea36988c5b08.png)

**Comment by rizsotto** [comment]
Yay, that's a good news... Is this a virtual machine that you can increase the size of the memory? Or can you increase the size of the swap space? Or check if you are running the build parallel and reduce the parallelism to lower the number of processes running at the same time?

Otherwise we need to go into the details... Check the allocation of Bear processes? (it's `intercept`, `citnames` and `bear`) Check how much memory you have? How much parallelism do you use? In order to fix this, I need to know these to reproduce the problem.

But thank you to try out those changes. I think we are close to get a compilation database for you! :smile:

**Comment by AimerYi** [comment]
@rizsotto  after increse the memory to 2GB ，the bear can work without any error ,thank u very much ,have a nice day!
