### ISSUE TITLE
New feature request: Export compile_commands.json without making the whole project

### ISSUE THREAD

**Issue by MCMocoder** [rizsotto/Bear#404]
Like `compiledb -n make`

**Comment by rizsotto** [comment]
@MCMocoder - thanks for the request.

This is implemented as `bear parse-sh` on the `4.2.0-rc` branch - the
equivalent of `compiledb -n make`:

```sh
make -n | bear parse-sh | bear semantic --input -
```

- `make -n` prints the commands without building;
- `bear parse-sh` turns each line into an execution event;
- `bear semantic --input -` writes `compile_commands.json` from those events.

One difference from `compiledb`: instead of matching command lines with
regexes, `parse-sh` parses a defined subset of POSIX `sh`, and when it hits
something it doesn't understand it skips that line and says so on stderr
rather than guessing. It's best-effort, so interception is still better when
you can run the build.

It isn't released yet - could you build the `4.2.0-rc` branch and try it on
your project? Feedback before release would help.
