### ISSUE TITLE
The winget package doesn't exist

### ISSUE THREAD

**Issue by g-berthiaume** [rizsotto/Bear#464]
I'm trying to install the Bear package using `winget` on Windows 10.

When using the CLI, I get the following:
```powershell
$  winget install Bear
Multiple packages found matching input criteria. Please refine the input.
Name         Id           Source
---------------------------------
Alb The Bear 9WZDNCRDKJB0 msstore
Bear         the-sz.Bear  winget
```

The problem is that both sources are invalid
- [Alb The Bear](https://apps.microsoft.com/store/detail/alb-the-bear/9WZDNCRDKJB0?hl=fr-ci&gl=CI) is a children story 
- [the-sz.Bear](https://the-sz.com/products/bear/) is a GUI tool to track down GDI and User handle leaks.

Is Bear supported on Windows?

**Comment by rizsotto** [comment]
Hey @g-berthiaume , I don't think Bear has a windows package.

The way Bear is working can work on Windows, but the code is using POSIX API calls (and not Windows API). So, somebody who has experience with the Windows API could make PRs to make that happen. (I am happy to guide/help this process.)

I'm closing this ticket, because the #431 is already tracking it.
