### ISSUE TITLE
bear produce empty compile_commands.json in ubuntu enviroment

### ISSUE THREAD

**Issue by ewall-cauc** [rizsotto/Bear#487]
**Describe the bug**
bear produce empty compile_commands.json in ubuntu enviroment
ps: i am newbie about ubuntu source build system, i guess it maybe the problem with chroot or somewhat, bear has simple usage exmaple, could someone give me help how to use bear with sbuild?

**To Reproduce**
1. vagrant ssh ubuntu && apt-get source procps
2. mk-sbuild --distro=ubuntu --arch=amd64 focal 
3. bear sbuild -d focal --arch=amd64 ./procps_3.3.16-1ubuntu2.3.dsc

**Expected behavior**
compile_commands.json with information abort procps build

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 20.04.5 LTS
 - OS architecture: x86_64
 - Bear version:  3.0.20
 - Bear install method:  apt-get install bear

**Additional context**
 - Can you give us a reference to the project that you are running against this tool?  just procps ubuntu source 
 - What build tools this project is using? sbuild
 - What architecture you are trying to compile for? x86-64

**Before you send...**
 - Have you read the `README.md` file or `man bear`? yes 
 - Have you looked what other open issues Bear has? yes
 - Are you sure that the build works without Bear? yes

**Comment by rizsotto** [comment]
Hey @ewall-cauc , thanks for the report.

What you are trying to do is capturing the package build, which are not regular builds. Package builds are try to be reproducing the same output for the same input. Therefore the package builder infrastructure is protecting the environment to be isolated and filter out changes. While Bear, is trying to change the environment and intrude the build (hijack the compiler calls).

Short answer, it won't work this way.

Long answer is harder... Because I am not sure what are you trying to achieve... Usually people want to have the compilation database of the project that they are working on. And those builds are okay and easy to manipulate. (Like a project is build with `make all`, then with Bear it become `bear -- make all`.) Usually you call your build system while you are developing software. The packaging (and package builds) are run when you release your software... Developers need the compilation database while they are developing the software, not when they are released it.

**Comment by ewall-cauc** [comment]
thx for your explicit reply，i figure out 1. ubuntu package system expect fixed isolate enviroment, bear maybe break it, take effect on evently result. 2. actually, in this situation i want debug the package that ubuntu release in repository, recompile the whole package through the source code will help me better understand what package do, and recompile through bear it will output compile_commands.json make VSCODE better display,  remove some macro definitions and unnecessary branches code will not run, help me quick understand what code do

**Comment by rizsotto** [comment]
If I got it correctly, you want to understand how `procps` is working. Is that correct? Then I would suggest to install the development dependencies of the package, download the source of `procps` and build it as its `INSTALL.md` file says (so not with `sbuild`). That will use `make`, which will work with Bear, so you can have a nice compilation database.

**Comment by ewall-cauc** [comment]
thx, i have solve it by use low level build package toools, ./debian/rule build with no chroot enviroment, addition with DEB_BUILD_OPTIONS=nocheck it will not run any build-time test suite provided by the package
