### ISSUE TITLE
building: grpc_dependency builds googletest

### ISSUE THREAD

**Issue by GitMensch** [rizsotto/Bear#495]
**Describe the bug**

**To Reproduce**
* have grpc not installed
* configure with `cmake -DENABLE_UNIT_TESTS=OFF -DENABLE_FUNC_TESTS=OFF` then `make`
* see that grpc checks for googletest, then does a checkout if its repo and builds it

**Expected behavior**
* internal building grpc skips googletest if disabled for bear

**Environment:**
 - Bear install method: build from 3.0.20 artifact

**Comment by rizsotto** [comment]
https://github.com/rizsotto/Bear/blob/master/third_party/grpc/CMakeLists.txt#L46

**Comment by GitMensch** [comment]
This is strange, because when I _manually_ pass it to bear I get a warning that it isn't used, but googletest is not build in the sub, I I don't specify it for bear it is build ?!?

I don't know much about cmake, but _guess_ all arguments given to bear are passed?
It would still be strange that this option is not used.... Is there something like "config.log" for autotools builds in cmake that shows the parameters passed?

**Comment by rizsotto** [comment]
Bear is using CMake subprojects. And not all arguments are passed down to the subprojects. (Each dependency has it's own `CMakeList.txt` file which controls what that subproject will see.)

When I set up the project years ago, I did verify that it does not run the unit tests of gRPC package. It might check out the sources (because git submodules), but it does not mean it builds too. How did you come to the conclusion that it builds and run the tests for gRPC?

**Comment by GitMensch** [comment]
> How did you come to the conclusion that it builds and run the tests for gRPC?

It took quite some time and said googletest and was within the gRPC.

> It might check out the sources (because git submodules), but it does not mean it builds too.

Hm, this _may_ be the case then. Can those submodules be deactivated?
Note: I did build from the 3.0.20 release, not from git checkout directly - but have seen several checkouts for the dependencies.

**Comment by rizsotto** [comment]
When you have Bear sources (from release or from git HEAD), it will checks for its dependencies. If it does not found on your machine it will build the dependency package from source. In case of gRPC, it gets the sources (of gRPC) from a git checkout. And because that git repository has git submodules, it will check out those repositories. (No control over that process, because it's at git level, not the build level.)

The only optimalization of this git checkout I've made, that it's a shallow clone (no complete history). Probably can this optimized further (PR is welcome), but the best thing if you have the dependency already installed on the machine.

I close this ticket now.
