### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

### ISSUE THREAD

**Issue by yong580** [rizsotto/Bear#517]
**Describe the bug**
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/bear/libear.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**To Reproduce**
I install bear use the command :
$ sudo apt install bear
I want to compile the Linux kernel and the error arise
Then I try to use bear to create a compile_commands.json
I use the command:
$bear -vvvv -l /usr/lib/x86_64-linux-gnu/bear/libear.so make 
Then the bug arise.
without bear I compile it successfully

**Expected behavior**
create a compile_commands.json for linux kernel

**Environment:**
 WSL2 Ubuntu

**Comment by rizsotto** [comment]
Hey @yong580, sorry, but I will close this ticket because it's not the problem of this project. (If you search for issues with the "wrong ELF class" text, you will find a [couple of reports](https://github.com/rizsotto/Bear/issues?q=is%3Aissue+wrong+ELF+class) like this.)

Tip: check if you have a multilib environment. (when 32bit and 64bit executables are mixed in the build)
