### ISSUE TITLE
Cannot open /usr/local/bin/bear: No such file

### ISSUE THREAD

**Issue by Aksl-B** [rizsotto/Bear#587]
**Describe the bug**
After building & installing bear as described in INSTALL.md, when I try to run with `bear -- make`, I get the single-line error :
```/bin/sh: 0: cannot open /usr/local/bin/bear: No such file```

**To Reproduce**
- Download the sources
- Make a "build" directory and cd inside
- Run cmake -DENABLE_UNIT_TESTS=OFF -DENABLE_FUNC_TESTS=OFF -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu ..
- Run make all
- Run make install DESTDIR=install (I don't have the rights to write to /usr)
- Put the folder containing bear in the PATH

**Expected behavior**
Upon executing `bear -- make`, I expect bear to create a compile_command.json file (preferably without error)

**Environment:**
 - OS name: Linux
 - OS version: Debian 6.1.94-1
 - OS architecture: x86_64
 - Bear version: 3.1.4
 - Bear install method: Built from source

**Additional context**
- The build process went well and produced an executable file named "bear" as expected
- Indeed, there is no file named "bear" in /usr/local/bin, and I don't expect there to be, I meant to keep the executable in (a subdirectory of) ~/opt
- I'm building from source since I don't have rights to install packages (I'm on a company computer)
- I don't have rights to write in /usr either
- If I run `make install` without setting destination directory, I get the following error message (related to missing write permissions) :
```
[ 19%] Built target grpc_dependency
[ 19%] Built target googletest_dependency
[ 39%] Built target nlohmann_json_dependency
[ 58%] Built target fmt_dependency
[ 78%] Built target spdlog_dependency
[100%] Built target BearSource
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/.
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot set permissions on "/usr/local/.": Operation not permitted.
```
- But since I have write permissions on ~/opt, I wanted to `make install` bear there, and it worked well, but now I can't execute bear (see the error message above)

Thank you for your time ! Tell me if anything is unclear :)

**Comment by rizsotto** [comment]
Please google for CMake documentation about how to override install directory.

**Comment by cgy233** [comment]
I ran into the same issue and found a reliable solution. The root cause is that some parts of the code or build scripts may hardcode `/usr/local/bin/bear`, which doesn't work in environments without root access.

### ✅ Here's how I fixed it:

1. Clone the Bear source code.
2. Search the source tree for hardcoded `/usr/local/bin/bear` and **replace it with** `~/.local/bin/bear`. For example:

   ```bash
   grep -rl '/usr/local/bin/bear' ./ | xargs sed -i 's|/usr/local/bin/bear|~/.local/bin/bear|g'
   ```
3. Then build and install Bear with a custom prefix:

   ```bash
   cd ~/tools/Bear/build
   cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local
   make
   make install
   ```
4. Ensure `~/.local/bin` is in your `PATH`.

Now `bear -- make` works as expected, and no reference to `/usr/local/bin` is needed.

Hope this helps someone running into the same problem!

---

（中文提示：可以全文搜索 `/usr/local/bin/bear`，改为你自己的安装目录，例如 `~/.local/bin/bear`，然后重新构建和安装）
