### ISSUE TITLE
Bear does not preserve single quotes in command line macro definitions 

### ISSUE THREAD

**Issue by PappasBrent** [rizsotto/Bear#588]
**Describe the bug**
Bear does not appear to preserve single quotes in command line macro definitions, and produces incorrect results when a compile command uses single quotes in command line macro definitions.

**To Reproduce**

1. Create a file `foo.c` with the following contents:

```c
int main(void) {
        FOO;
        return 0;
}
```

2. Create a `makefile` with the following contents (notice the single quotes around the definition of `FOO`):

```make
main:
	cc foo.c -DFOO='"test"' -o foo
```

3. Build `foo.c`, intercepting the build with `bear`:

```sh
bear -- make
```

4. The resulting `compile_commands.json` file will contain a single object, whose `arguments` field should look like this (I've also numbered the lines here):

```json
1 "arguments": [
2     "/usr/bin/cc",
3      "-c",
4      "-DFOO=\"test\"",
5      "-o",
6      "foo",
7      "foo.c"
8    ],
```

Notice that on line 4, the single quotes in the definition of the macro `FOO` are not preserved.
This means that if I try to run the command by combining the arguments back into a single string, e.g.,

```sh
/usr/bin/cc -c -DFOO="test" -o foo foo.c
```

the build will fail with undefined references to the declaration `test`.
Because the single quotes are not preserved, the expansion of `FOO` becomes `test`, not `"test"` as it originally was.
This breaks the original behavior of the build system.

**Expected behavior**
`bear` should preserve single quotes in command line macro definitions.
This means that for the previous example, line 4 should be `"-DFOO='\"test\"',` (notice the single quotes).

**Environment:**
 - OS name: Linux
 - OS version: Ubuntu 22.04.4
 - OS architecture: x86_64
 - Bear version: `3.0.18`
 - Bear install method: from PyPi via `pip`

**Additional context**
 > Can you give us a reference to the project that you are running against this tool? 

Yes. I am running into this issue when attempting to use `bear` to intercept the Linux kernel's build system.

 > What build tools this project is using?

GNU make wtih `configure` script.
 
> What architecture you are trying to compile for?

x86_64 (same as host).

**Comment by rizsotto** [comment]
Hi @PappasBrent , thanks for your detailed report.

Had this kind of complaint many times before. And I am pretty sure the output is valid.

The flaw of your thought process that you think the JSON array can be just concatenated and insert to the shell again. That's not correct assumption. Let me demonstrate this...

```sh
cd /tmp
$ mkdir test
$ mkdir "test"
mkdir: cannot create directory ‘test’: File exists
```

Which shows that the shell itself swallows the quotes.

```python
>>> import subprocess
>>> subprocess.run(['ls', '-l', '/tmp/test'])
total 0
CompletedProcess(args=['ls', '-l', '/tmp/test'], returncode=0)
>>> subprocess.run(['ls', '-l', '/tmp/"test"'])
ls: cannot access '/tmp/"test"': No such file or directory
CompletedProcess(args=['ls', '-l', '/tmp/"test"'], returncode=2)
```

Using Python `subprocess` module, you can see that the quotes are preserved and differentiated.

I would like to add two things to this story:
- The Bear output is defined in [this page](https://clang.llvm.org/docs/JSONCompilationDatabase.html). The main consumer of the output file is the tooling library. Therefore it is expected to consumed by programs.
- You can configure Bear to produce the output file entries to have `command` (instead of the `arguments`) field. That is more "shell friendly" format and can be copy-pasted to the shell directly.

**Comment by PappasBrent** [comment]
Hi @rizsotto , thank you for the thoughtful response.
I'll use the `command` field instead of the `args` field going forward; that should solve my problem.
