### ISSUE TITLE
error log while bear make

### ISSUE THREAD

**Issue by henry-y** [rizsotto/Bear#78]
ERROR: ld.so: object '/usr/local/lib/libear.so' from LD_PRELOAD cannot be preloaded: ignored.

What could be the cause, please?

BTW, make check       passed.

**Comment by rizsotto** [comment]
thanks for the report. to help you i need more information. did you install Bear from source? or did you use some distribution packages? if you were doing from source, did you say 'make install' as well? is the file '/usr/local/lib/libear.so' exists? thanks in advance.

**Comment by henry-y** [comment]
@rizsotto I installed Bear from source, and make install, /usr/local/lib/libear.so exists as well:

# ldd /usr/local/lib/libear.so
        linux-vdso.so.1 =>  (0x00007fff04ffe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f84a14d9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f84a1119000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f84a18fd000)

**Comment by rizsotto** [comment]
great, could you also tell which OS, which distro you are using? when you get this error message what is the command line you gave? is it involve fakeroot/chroot during compilation?

**Comment by henry-y** [comment]
OS is Ubuntu 12.04.5 LTS
the command line I gave is just: bear make
I'm not very sure if there's any fakeroot/chroot during compilation, how will that affect Bear?

**Comment by rizsotto** [comment]
thanks, could you also provide the source that you try to build with 'bear make'? then later when i'm back from travelling will try to reproduce the issue.

**Comment by henry-y** [comment]
Unfortunately I can't provide the source to you for some reason, besides,
there are too many.

2015-03-06 23:50 GMT+08:00 László Nagy <notifications@github.com>:

**Comment by ff2000** [comment]
You could try LD_DEBUG=all bear make to get further infos.
And just a wild guess: You are not trying to use your 64bit bear together with a 32bit compiler, don't you?

**Comment by rizsotto** [comment]
@ff2000 thanks for your help. I also had the same guess.
@henry-y I was not able to reproduce this bug. Could you send me the output of the 'LD_DEBUG=all bear make' command generate?

**Comment by rizsotto** [comment]
thank you guys for the help!

**Comment by rizsotto** [comment]
@enter-the-bot i think if you compile it as 32-bit library it will work. (pass `-m32` somehow to the compiler.)

**Comment by nolange** [comment]
Since I use quite a few toolchains, I ran into in this issue before. PArticularly bad if the build process mixes 64 and 32bit tools.
I just found a really nice solution: don`t use the absolute path for the libear.so. Install the 32 and 64 bit libraries in the multilib paths:
/usr/lib/i386-linux-gnu/libear.so
/usr/lib/x86_64-linux-gnu/libear.so

and run with "bear -l libear.so"

Is there any reason to use the absolute path as default btw? Would be great if you could change it.

**Comment by rizsotto** [comment]
thanks @nolange, interesting what you say.

on OSX the multilib situation is easier. (you can create a single lib which can be used for 32 and 64 programs) would be nice to have something like that on linux too.

the path was absolute, because it does not require the lib to be installed on a well known location. `man ld.so` explains the search path rules for `LD_PRELOAD`.

will think about it to make this change, because more and more bug reports coming for this issue.
