### ISSUE TITLE
Support for linking?

### ISSUE THREAD

**Issue by stepthom** [rizsotto/Bear#84]
Hi,

Bear is great and I use it a lot.

I've come across a use case wherein I'd like to know the link command(s) used to build the final executable(s). Does Bear have the ability to capture this information?

**Comment by rizsotto** [comment]
hi Stephen, thanks for the message! Bear actually does have this information and it filters out those cases. (Because those shall not go into the compilation database.) Commands like `cc -o prg.exec file1.c file2.c` considered as compilation and those could be found in the final report.
what i would recommend to call Bear with `--disable-filter` option, it generates a JSON file with all child processes. this you can post-process and filter out the link commands.

Bear major goal is to produce compilation database files which can be used for Clang tooling. link commands are not welcomed by these tools, that's why i would not implement it. if you feel to add this functionality (adding extra switch like `--with-link-commands`) send me a patch.

**Comment by stepthom** [comment]
@rizsotto Didn't know about the `--disable-filter` option. I'll give that a shot!

And yes, if I add this functionality, I'll be sure to forward it on to you.

Thanks!
