### ISSUE TITLE
 ld.so: object '/usr/local/lib/libear.so' from LD_PRELOAD cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by aamen110** [rizsotto/Bear#92]
build in 32bit os
when I use in 64bit os get this error

**Comment by aamen110** [comment]
And
I build in 64bit .
it works fun in 64bit os.

**Comment by aamen110** [comment]
why wontfix
should I build two lib for 32bit os and 64bit os ?

**Comment by rizsotto** [comment]
you are right. i am sorry to just put it in wontfix category and not explain it... but to my best knowledge you can't make a single library which works for 32 and 64 at the same time. (i might be wrong here.) please tell me (or even better: send a patch) if you know what needs to be changed on Bear in order to make that happen.
